---
title: "Advent of Code - Solutions"
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "2021-12-2"
knit: (function(inputFile, encoding) {
   rmarkdown::render(inputFile, encoding = encoding, output_file = "index.html", output_dir = here::here("docs")) })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 2024

* [Day 1](2024_task1.html)
* [Day 2](2024_task2.html)
* [Day 3](2024_task3.html)
* [Day 4](2024_task4.html)
* [Day 5](2024_task5.html)
* [Day 6](2024_task6.html)
* [Day 7](2024_task7.html)
* [Day 8](2024_task8.html)
* [Day 9](2024_task9.html)
* [Day 10](2024_task10.html)
* [Day 11](2024_task11.html)
* [Day 12](2024_task12.html)
* [Day 13](2024_task13.html)
* [Day 14](2024_task14.html)
* [Day 15](2024_task15.html)
* [Day 16](2024_task16.html)
* [Day 17](2024_task17.html)
* [Day 18](2024_task18.html)
* [Day 19](2024_task19.html)
* [Day 20](2024_task20.html)
* [Day 21](2024_task21.html)
* [Day 22](2024_task22.html)
* [Day 23](2024_task23.html)
* [Day 24](2024_task24.html)
* [Day 25](2024_task25.html)

# 2023

* [Day 1](2023_task1.html)
* [Day 2](2023_task2.html)
* [Day 3](2023_task3.html)
* [Day 4](2023_task4.html)
* [Day 5](2023_task5.html)
* [Day 6](2023_task6.html)
* [Day 7](2023_task7.html)
* [Day 8](2023_task8.html)
* [Day 9](2023_task9.html)
* [Day 10](2023_task10.html)
* [Day 11](2023_task11.html)
* [Day 12](2023_task12.html)
* [Day 13](2023_task13.html)

# 2022

* [Day 1](2022_task1.html)
* [Day 2](2022_task2.html)
* [Day 3](2022_task3.html)
* [Day 4](2022_task4.html)
* [Day 5](2022_task5.html)
* [Day 6](2022_task6.html)
* [Day 7](2022_task7.html)
* [Day 8](2022_task8.html)
* [Day 9](2022_task9.html)
* [Day 10](2022_task10.html)
* [Day 11](2022_task11.html)
* [Day 12](2022_task12.html)
* [Day 13](2022_task13.html)
* [Day 14](2022_task14.html)
* [Day 15](2022_task15.html)
* [Day 16](2022_task16.html)
* [Day 17](2022_task17.html)
* [Day 18](2022_task18.html)
* [Day 19](2022_task19.html)
* [Day 20](2022_task20.html)
* [Day 21](2022_task21.html)
* [Day 22](2022_task22.html)
* [Day 23](2022_task23.html)
* [Day 24](2022_task24.html)
* [Day 25](2022_task25.html)

# 2021

* [Day 1](2021_task1.html)
* [Day 2](2021_task2.html)
* [Day 3](2021_task3.html)
* [Day 4](2021_task4.html)
* [Day 5](2021_task5.html)
* [Day 6](2021_task6.html)
* [Day 7](2021_task7.html)
* [Day 8](2021_task8.html)
* [Day 9](2021_task9.html)
* [Day 10](2021_task10.html)
* [Day 11](2021_task11.html)
* [Day 12](2021_task12.html)
* [Day 13](2021_task13.html)
* [Day 14](2021_task14.html)
* [Day 15](2021_task15.html)
* [Day 16](2021_task16.html)
* [Day 17](2021_task17.html)
* [Day 18](2021_task18.html)
* [Day 19](2021_task19.html)
* [Day 20](2021_task20.html)
* [Day 21](2021_task21.html)
* [Day 22](2021_task22.html)
* [Day 23](2021_task23.html)
* [Day 24](2021_task24.html)
* [Day 25](2021_task25.html)

# 2020

* [Day 1](2020_task1.html)
* [Day 2](2020_task2.html)
* [Day 3](2020_task3.html)
* [Day 4](2020_task4.html)
* [Day 5](2020_task5.html)
* [Day 6](2020_task6.html)
* [Day 7](2020_task7.html)
* [Day 8](2020_task8.html)
* [Day 9](2020_task9.html)
* [Day 10](2020_task10.html)
* [Day 11](2020_task11.html)
* [Day 12](2020_task12.html)
* [Day 13](2020_task13.html)
* [Day 14](2020_task14.html)
* [Day 15](2020_task15.html)
* [Day 16](2020_task16.html)
* [Day 17](2020_task17.html)
* [Day 18](2020_task18.html)
* [Day 19](2020_task19.html)
* [Day 20](2020_task20.html)
* [Day 21](2020_task21.html)
* [Day 22](2020_task22.html)
* [Day 23](2020_task23.html)
* [Day 24](2020_task24.html)
* [Day 25](2020_task25.html)

# 2019

* [Day 1](2019_task1.html)
* [Day 2](2019_task2.html)
* [Day 3](2019_task3.html)
* [Day 4](2019_task4.html)
* [Day 5](2019_task5.html)
* [Day 6](2019_task6.html)
* [Day 7](2019_task7.html)
* [Day 8](2019_task8.html)
* [Day 9](2019_task9.html)
* [Day 10](2019_task10.html)
* [Day 11](2019_task11.html)
* [Day 12](2019_task12.html)
* [Day 13](2019_task13.html)
* [Day 14](2019_task14.html)
* [Day 15](2019_task15.html)
* [Day 16](2019_task16.html)
* [Day 17](2019_task17.html)
* [Day 18](2019_task18.html)
* [Day 19](2019_task19.html)
* [Day 20](2019_task20.html)
* [Day 21](2019_task21.html)
* [Day 22](2019_task22.html)
* [Day 23](2019_task23.html)
* [Day 24](2019_task24.html)
* [Day 25](2019_task25.html)

# 2018

* [Day 1](2018_task1.html)
* [Day 2](2018_task2.html)
* [Day 3](2018_task3.html)
* [Day 4](2018_task4.html)
* [Day 5](2018_task5.html)
* [Day 6](2018_task6.html)
* [Day 7](2018_task7.html)
* [Day 8](2018_task8.html)
* [Day 9](2018_task9.html)
* [Day 10](2018_task10.html)
* [Day 11](2018_task11.html)
* [Day 12](2018_task12.html)
* [Day 13](2018_task13.html)
* [Day 14](2018_task14.html)
* [Day 15](2018_task15.html)
* [Day 16](2018_task16.html)
* [Day 17](2018_task17.html)
* [Day 18](2018_task18.html)
* [Day 19](2018_task19.html)
* [Day 20](2018_task20.html)
* [Day 21](2018_task21.html)
* [Day 22](2018_task22.html)
* [Day 23](2018_task23.html)
* [Day 24](2018_task24.html)
* [Day 25](2018_task25.html)

# 2017

* [Day 1](2017_task1.html)
* [Day 2](2017_task2.html)
* [Day 3](2017_task3.html)
* [Day 4](2017_task4.html)
* [Day 5](2017_task5.html)
* [Day 6](2017_task6.html)
* [Day 7](2017_task7.html)
* [Day 8](2017_task8.html)
* [Day 9](2017_task9.html)
* [Day 10](2017_task10.html)
* [Day 11](2017_task11.html)
* [Day 12](2017_task12.html)
* [Day 13](2017_task13.html)
* [Day 14](2017_task14.html)
* [Day 15](2017_task15.html)
* [Day 16](2017_task16.html)
* [Day 17](2017_task17.html)
* [Day 18](2017_task18.html)
* [Day 19](2017_task19.html)
* [Day 20](2017_task20.html)
* [Day 21](2017_task21.html)
* [Day 22](2017_task22.html)
* [Day 23](2017_task23.html)
* [Day 24](2017_task24.html)
* [Day 25](2017_task25.html)

# 2016

* [Day 1](2016_task1.html)
* [Day 2](2016_task2.html)
* [Day 3](2016_task3.html)
* [Day 4](2016_task4.html)
* [Day 5](2016_task5.html)
* [Day 6](2016_task6.html)
* [Day 7](2016_task7.html)
* [Day 8](2016_task8.html)
* [Day 9](2016_task9.html)
* [Day 10](2016_task10.html)
* [Day 11](2016_task11.html)
* [Day 12](2016_task12.html)
* [Day 13](2016_task13.html)
* [Day 14](2016_task14.html)
* [Day 15](2016_task15.html)
* [Day 16](2016_task16.html)
* [Day 17](2016_task17.html)
* [Day 18](2016_task18.html)
* [Day 19](2016_task19.html)
* [Day 20](2016_task20.html)
* [Day 21](2016_task21.html)
* [Day 22](2016_task22.html)
* [Day 23](2016_task23.html)
* [Day 24](2016_task24.html)
* [Day 25](2016_task25.html)

# 2015

* [Day 1](2015_task1.html)
* [Day 2](2015_task2.html)
* [Day 3](2015_task3.html)
* [Day 4](2015_task4.html)
* [Day 5](2015_task5.html)
* [Day 6](2015_task6.html)
* [Day 7](2015_task7.html)
* [Day 8](2015_task8.html)
* [Day 9](2015_task9.html)
* [Day 10](2015_task10.html)
* [Day 11](2015_task11.html)
* [Day 12](2015_task12.html)
* [Day 13](2015_task13.html)
* [Day 14](2015_task14.html)
* [Day 15](2015_task15.html)
* [Day 16](2015_task16.html)
* [Day 17](2015_task17.html)
* [Day 18](2015_task18.html)
* [Day 19](2015_task19.html)
* [Day 20](2015_task20.html)
* [Day 21](2015_task21.html)
* [Day 22](2015_task22.html)
* [Day 23](2015_task23.html)
* [Day 24](2015_task24.html)
* [Day 25](2015_task25.html)

