---
params:
   task_nr: 2
   year: 2023
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L)
  }
  text_block <- text_block[nzchar(text_block)]
  id <- str_extract(text_block, "\\d+")
  games <- text_block %>% 
    str_remove("Game \\d+: ") %>% 
    str_split("; ?")
  map2(id, games, function(id, game) {
    stats <- str_match_all(game, "(?<nr>\\d+) (?<color>red|blue|green)")
    map(stats, ~ .x[, "nr"] %>% 
      as.integer() %>% 
      as.list() %>% 
      set_names(.x[, "color"]) %>% 
      as_tibble()) %>% 
      list_rbind() %>% 
      mutate(id = as.integer(id), .before = 1L)
  }) %>% 
    list_rbind()
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We need to check per game if all numbers are below the threshold. THen, we need to sum
the respective ids.

```{r get-solution-1}
count_valid_games <- function(games, limits = c(red = 12L, green = 13L, blue = 14L)) {
  games %>% 
    group_by(id) %>% 
    summarize(is_valid = all(blue <= limits["blue"] & 
                               red <= limits["red"] & 
                               green <= limits["green"], na.rm = TRUE)) %>% 
    filter(is_valid) %>% 
    summarize(chk = sum(id)) %>% 
    pull(chk)
}

count_valid_games(puzzle_data)

```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

For the second part we use `pmax` to get the parallel maxima per game draw. The `power` is
then the product of these maxima.

```{r get-solution-2}
calculate_power <- function(games) {
  games %>% 
    group_by(id) %>% 
    summarize(power =
      cbind(red, green, blue) %>% 
        t() %>% 
        as.data.frame() %>% 
        as.list() %>% 
        c(na.rm = TRUE) %>% 
        do.call(pmax, .) %>% 
        prod()
    ) %>% 
    pull(power) %>% 
    sum()
}

calculate_power(puzzle_data)
```
