---
params:
   task_nr: 8
   year: 2017
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_split(" ") %>% 
    do.call(rbind, .) %>% 
    set_colnames(c("reg", "op", "n", ".skip", "cond_reg", "cond_eq", "cond_n")) %>% 
    as_tibble() %>% 
    mutate(across(ends_with("n"), as.integer)) %>% 
    select(-.skip)
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- c(0L, 2L, 7L, 0L)
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We write a parser, which uses a list as register.

```{r get-solution-1}
parse_line <- function(reg, op, n, cond_reg, cond_eq, cond_n, register) {
  ## first check whether the registers are already present, if not create them
  if (!reg %in% names(register)) {
    register[[reg]] <- 0L
  }
  if (!cond_reg %in% names(register)) {
    register[[cond_reg]] <- 0L
  }
  cond <- do.call(cond_eq, list(register[[cond_reg]], cond_n))
  if (cond) {
    sign <- if_else(op == "dec", -1L, 1L)
    register[[reg]] <- register[[reg]] + sign * n
  }
  register
}

evaluate_ops <- function(ops = puzzle_data, return_max = FALSE) {
  max_val <- -Inf
  register <- list()
  for (i in 1:nrow(ops)) {
    line <- ops %>% 
      slice(i) %>% 
      as.list()
    line$register <- register
    register <- do.call(parse_line, line)
    max_val <- max(c(max_val, unlist(register)))
  }
  if (return_max) {
    max_val
  } else {
    max(unlist(register))
  }
}
evaluate_ops(puzzle_data)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

We keep track about the intermediate results and return their maximum.

```{r get-solution-2}
evaluate_ops(puzzle_data, TRUE)
```
