---
params:
   task_nr: 22
   year: 2018
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}

```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
library(collections)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  res <- text_block %>% 
    str_extract_all("\\d+") %>% 
    set_names("depth", "target") %>% 
    lapply(as.numeric)
  res$target <- matrix(res$target[2:1], ncol = 2L, 
                       dimnames = list(NULL, c("row", "col"))) + 1L
  res
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- list(target = matrix(11, ncol = 2, 
                                     dimnames = list(NULL, c("row", "col"))),
                     depth = 510L)
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]] %>% 
      str_replace_all("\\$", "\\\\$"))
```

### Solution

```{r get-solution-1, cache = TRUE}
print.erosion <- function(x, ...) {
  cave <- x 
  cave[] <- c(".", "=", "|")[x + 1L]
  cave[1, 1] <- "M"
  cave[attr(x, "target")] <- "T"
  x <- apply(cave, 1L, paste, collapse = "") %>% 
    paste(collapse = "\n")
  cat(x, "\n")
  invisible(x)
}

create_cave <- function(target = puzzle_data$target, 
                        depth = puzzle_data$depth,
                        extend = 0L, add = TRUE) {
  n <- target[, "row"]
  m <- target[, "col"]
  if (add) {
    n <- n + extend
    m <- m + extend
  } else {
    n <- n * extend
    m <- m * extend
  }
  cave <- matrix(NA_integer_, n, m)
  cave[1, ] <- (c(0L, 16807L * seq_len(m - 1L)) + depth) %% 20183L
  cave[, 1] <- (c(0L, 48271L * seq_len(n - 1L)) + depth) %% 20183L
  for (i in 2:n) {
    for (j in 2:m) {
      if (i == target[, "row"] && j == target[, "col"]) {
        cave[i, j] <- depth %% 20183L
      } else {
        cave[i, j] <- ((cave[i - 1L, j] * cave[i, j - 1L]) + depth) %% 20183L
      }
    }
  }
  cave <- cave %% 3L
  attr(cave, "target") <- target
  class(cave) <- "erosion"
  cave
}

cave <- create_cave(puzzle_data$target, puzzle_data$depth, 15L)

sum(cave[seq(1L, puzzle_data$target[, "row"]),
         seq(1, puzzle_data$target[, "col"])])
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

For the second part we us an A Star algorithm. We extend the cave by 15 pieces which
corresponds roughly twice the tool changing time.


```{r get-solution-2, cache = TRUE}
heuristic <- function(pos, target, tool) {
  sum(abs(c(target) - c(pos))) + (tool != 1L) * 7L
}

find_shortest_path <- function(cave) {
  dirs <- rbind(
    "^" = c(-1L, 0L),
    ">" = c(0L, 1L),
    "v" = c(1L, 0L),
    "<" = c(0L, -1L)
  )
  n <- nrow(cave)
  m <- ncol(cave)
  n_tools <- 3L
  n_terrain <- 3L

  ## each matrix represents the change from current (column) to new (row) terrain
  ## if we hold a certain tool (3rd dimension)
  tool_changes <- array(c(1L, 2L, 1L, NA_integer_, NA_integer_, NA_integer_, 1L, 3L, 1L,
                          2L, 2L, 1L, 2L, 2L, 3L, NA_integer_, NA_integer_, NA_integer_,
                          NA_integer_, NA_integer_, NA_integer_, 2L, 3L, 3L, 1L, 3L, 3L),
                        c(n_terrain, n_terrain, n_tools), 
                        dimnames = list(c("rocky", "wet", "narrow"),
                                        c("rocky", "wet", "narrow"),
                                        c("torch", "climbing gear", "empty")))
  make_key <- function(pos, tool) {
    (pos[1] - 1L) * m + pos[2] + 
      (tool - 1L) * n * m
  }  

  get_neighbors <- function(pos, tool) {
    nbs <- t(t(dirs) + c(pos))
    ## no neighbors outside the cave
    nbs <- nbs[
      between(nbs[, 1L], 1L, nrow(cave)) & 
        between(nbs[, 2L], 1L, ncol(cave)), , 
      drop = FALSE
    ]
    from <- cave[pos]
    to <- cave[nbs]
    idx <- cbind(to + 1L, from + 1L, tool)
    new_tool <- tool_changes[idx]
    cbind(
      nbs, 
      costs = (tool != new_tool) * 7L + 1L,
      tool = new_tool
    )
  }
  start <- cbind(1L, 1L)
  target <- attr(cave, "target")
  start_tool <- 1L
  
  pq <- priority_queue()
  max_states <- n * m * n_tools
  f_score <- g_score <- rep(.Machine$integer.max, max_states)
  
  start_key <- make_key(start, start_tool)
  g_score[start_key] <- 0L
  f_score[start_key] <- heuristic(start, target, start_tool)
  
  pq$push(cbind(start,
                tool = start_tool),
          -f_score[[start_key]])
  while (pq$size() > 0) {
    status <- pq$pop()
    pos <- status[, 1:2, drop = FALSE] 
    key <- make_key(pos, status[, 3L])
    
    if (all(pos == target)) {
      ## we reached the goal
      return(g_score[key] + (status[, 3L] != 1L) * 7L)
    }
    
    nbs <- get_neighbors(pos, status[, 3L])
    for (nb_idx in seq_len(nrow(nbs))) {
      nb <- nbs[nb_idx, , drop = FALSE]
      nb_pos <- nb[, 1:2, drop = FALSE]
      nb_tool <- nb[, "tool"]
      nb_key <- make_key(nb_pos, nb_tool)
      g_new <- g_score[key] + nb[, "costs"]
      if (g_score[nb_key] > g_new) {
        g_score[nb_key] <- g_new
        f_score[nb_key] <- g_new + heuristic(nb_pos, target, nb_tool)
        pq$push(cbind(nb_pos, tool = nb_tool), -f_score[nb_key])
      }
    }
  }
  FALSE
}
find_shortest_path(cave)
```
