---
params:
   task_nr: 19
   year: 2017
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_split("") %>% 
    do.call(rbind, .)
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We start at the top left corner and move along he directions. To do so, we keep track of
the current direction of movement (horizontal vs. vertical) and change it only at 
crossroads.

```{r get-solution-1}
collect_letters <- function(path) {
  start <- cbind(row = 1L, col = which(path[1, ] != " ")[1L])
  dirs <- rbind(
    ">" = c(0L, 1L),
    "v" = c(1L, 0L),
    "<" = c(0L, -1L),
    "^" = c(-1L, 0L)
  )
  nr_loots <- sum(!path %in% c(" ", "-", "|", "+"))
  cur_dir <- 2L
  pos <- start
  loot <- character(0L)
  steps <- 1L
  while (length(loot) < nr_loots) {
    steps <- steps + 1L
    pos <- t(t(dirs[cur_dir, , drop = FALSE]) + c(pos))
    next_field <- path[pos]
    if (next_field == "+") {
      ## we need to change direction
      nbs <- path[t(t(dirs) + c(pos))]
      target <- if_else(cur_dir %% 2L == 0L, "-", "|")
      cur_dir <- which(nbs == target)
    } else if (!next_field %in% c("-", "|")) {
      ## we reached a letter -> include it
      loot <- c(loot, next_field)
    }
  }
  list(path = loot %>% 
    paste(collapse = ""),
    steps = steps)
}

res <- collect_letters(puzzle_data)

res$path
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

We need to return the number of steps we took.

```{r get-solution-2}
res$steps
```
