---
params:
   task_nr: 12
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   o_file <- sprintf("%s_%s", format(Sys.Date(), "%Y"), 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
width: 100%;
}

.back {
font-size: 2rem;
}

.day-desc {
border: 2px dotted;
border-radius: 6px;
border-color: var(--blockquote-border-color);
padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center")
## Define a function to write text in typewriter font
tt <- function(x) {
	if (knitr::is_latex_output()) {
		sprintf("\\texttt{%s}", as.character(x))
	} else if (knitr::is_html_output()) {
		sprintf("<tt>%s</tt>", as.character(x))
	} else {
		x
	}
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(tibble)
library(dplyr)
library(purrr)
library(igraph)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/2021/day/", params$task_nr)
puzzle <- GET(base_url,
				  session_cookie) %>% 
	content(encoding = "UTF-8") %>% 
	xml_find_all("///article") %>% 
	lapply(as.character)

## use curly braces in the last pipe to avoid that . is additionally added
## as the first argument
puzzle_data <- GET(paste0(base_url, "/input"),
						 session_cookie) %>% 
	content(encoding = "UTF-8") %>% 
	str_split("\n") %>% 
	`[[`(1) %>% 
		head(-1L) %>% 
	lapply(str2lang) %>% 
	do.call(graph_from_literal, .)

```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We use the library `igraph` to deal with the network. First of all, lets plot the graph:

```{r plot-graph}
V(puzzle_data)$single <- str_detect(V(puzzle_data)$name, "^[:lower:]+$")
V(puzzle_data)$color <- "#F9DB6D"
V(puzzle_data)[c("start", "end")]$color <- c("#464D77", "#36827F")
V(puzzle_data)[c("start", "end")]$label.color <- "white"
plot(puzzle_data, layout = layout_as_tree(puzzle_data, root = "start"))
```


```{r solution-a}
walk_graph <- function(vertex, path = list(), G = puzzle_data) {
	nbs <- 
	if (vertex$name == "end") {
		1
	} else if
	childs <- G[[vertex]]
	
}

```



## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

```{r solution-b, eval = length(puzzle) > 1}
```


