---
params:
   task_nr: 21
   year: 2017
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: TRUE
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  line2matrix <- function(line) {
    nr <- str_count(line, "/") + 1L
    line %>% 
      str_remove_all(fixed("/")) %>% 
      str_split("") %>% 
      extract2(1L) %>% 
      matrix(nrow = nr, byrow = TRUE)
  }
  text_block %>% 
    str_split(fixed(" => ")) %>% 
    map(~ list(
      input = line2matrix(.x[[1L]]),
      output = line2matrix(.x[[2L]])
      )
    )
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- parse_puzzle_data()
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

First of all, we amend the rule book by all rotations and flips on the input. Then, we 
loop through the initial picture and apply all rules that apply.

```{r get-solution-1}
transform <- function(input) {
  n <- nrow(input)
  
  # Define flip & rotation indices once
  if (n == 2L) {
    flip_idx <- list(
      h = c(2L, 1L, 4L, 3L),
      v = c(3L, 4L, 1L, 2L)
    )
    rot_idx <- c(2L, 4L, 1L, 3L)
  } else if (n == 3L) {
    flip_idx <- list(
      h = c(3L, 2L, 1L, 6L, 5L, 4L, 9L, 8L, 7L),
      v = c(7L, 8L, 9L, 4L, 5L, 6L, 1L, 2L, 3L)
    )
    rot_idx <- c(3L, 6L, 9L, 2L, 5L, 8L, 1L, 4L, 7L)
  }
  
  base <- c(input)
  res <- character(0L)
  
  cur <- base
  for (i in 1:4) {  # 4 rotations
    res <- c(res, paste(cur, collapse = ""))
    res <- c(res, vapply(flip_idx, function(idx) paste(cur[idx], collapse = ""), 
                         character(1L)))
    cur <- cur[rot_idx]
  }
  unique(res)
}


create_rule_book <- function(basic_rules) {
  rules <- list()
  for (rule in basic_rules) {
    trafs <- transform(rule$input)
    for (new_rule in trafs) {
      stopifnot("ambigious rule" = !new_rule %in% names(rules))
      rules[[new_rule]] <- rule$output
    }
  }
  rules
}

paint <- function(n, basic_rules = puzzle_data) {
  rule_book <- create_rule_book(basic_rules)
  res <- matrix(c(".", ".", "#", "#", ".", "#", ".", "#", "#"), 3L)
  ## prefer base R to speed up
  for (i in 1:n) {
    size <- nrow(res)
    width <- if_else(size %% 2L == 0L, 2L, 3L)
    I <- seq(1L, size, by = width)
    J <- 0:(width - 1L)
    dirs <- as.matrix(expand.grid(J, J))
    k <- size / width
    new_res <- vector("list", k * k)
    idx <- as.matrix(expand.grid(I, I))
    for (block in seq_len(nrow(idx))) {
      start <- idx[block, ]
      pos <- t(t(dirs) + start)
      key <- paste(res[pos], collapse = "")
      if (!is.null(rule_book[[key]])) {
        new <- rule_book[[key]]
      } else {
        new <- matrix(str_split(key, "")[[1L]], width)
      }
      new_res[[block]] <- new
    }
    cols <- lapply(1:k, function(col) 
      do.call(rbind, new_res[((col - 1L) * k + 1L):(col * k)]))
    res <- do.call(cbind, cols)
  }
  sum(res == "#")
}
paint(5L, puzzle_data)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

We simply have to increase the number of iterations.

```{r get-solution-2, cache = TRUE}
paint(18L, puzzle_data)
```