---
params:
   task_nr: 21
   year: 2019
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
library(knitr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
 text_block %>% 
    str_split(",") %>% 
    do.call(c, .) %>% 
    as.numeric()
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We build upon the code from [Day 19 @ 2019](2019_task19.html).

```{r get-solution-1}
parse_op_codes_fast <- function(op_codes = puzzle_data, input = numeric(0L), 
                                verbose = FALSE) {
  ip <- 1L
  rel_base <- 0L
  
  out_buffer <- numeric(0)
  out_len <- 0L
  out_block <- 1024L
  block_size <- 1024L
  
  grow_memory <- function(idx) {
    if (idx > length(op_codes)) {
      new_size <- ceiling(idx / block_size) * block_size
      op_codes <<- c(op_codes, rep(0, new_size - length(op_codes)))
    }
  }
  
  append_out <- function(val) {
    if (out_len + 1L > length(out_buffer)) {
      new_size <- length(out_buffer) + out_block
      out_buffer <<- c(out_buffer, rep(0, new_size - length(out_buffer)))
    }
    out_len <<- out_len + 1L
    out_buffer[out_len] <<- val
  }
  
  get_val <- function(param, mode) {
    if (mode == 0L) {
      grow_memory(param + 1L)
      return(op_codes[param + 1L])
    } else if (mode == 1L) {
      return(param)
    } else if (mode == 2L) {
      idx <- rel_base + param + 1L
      grow_memory(idx)
      return(op_codes[idx])
    } else {
      stop("unknown mode")
    }
  }
  
  get_addr <- function(param, mode) {
    if (mode == 0L) {
      return(param + 1L)
    } else if (mode == 2L) {
      return(rel_base + param + 1L)
    } else {
      stop("invalid write mode")
    }
  }
  
  halt <- FALSE
  while (!halt) {
    instr <- op_codes[ip]
    op <- instr %% 100L
    modes <- c(
      (instr %/% 100L) %% 10L, 
      (instr %/% 1000L) %% 10L, 
      (instr %/% 10000L) %% 10L
    )
    
    if (op == 1L) { # add
      a <- get_val(op_codes[ip + 1L], modes[1L])
      b <- get_val(op_codes[ip + 2L], modes[2L])
      addr <- get_addr(op_codes[ip + 3L], modes[3L])
      grow_memory(addr)
      op_codes[addr] <- a + b
      ip <- ip + 4L
    } else if (op == 2L) { # mul
      a <- get_val(op_codes[ip + 1L], modes[1L])
      b <- get_val(op_codes[ip + 2L], modes[2L])
      addr <- get_addr(op_codes[ip + 3L], modes[3L])
      grow_memory(addr)
      op_codes[addr] <- a * b
      ip <- ip + 4L
    } else if (op == 3L) { # input
      if (length(input) == 0L) {
        stop("No input available")
      }
      addr <- get_addr(op_codes[ip + 1L], modes[1])
      grow_memory(addr)
      op_codes[addr] <- input[1L]
      input <- input[-1]
      ip <- ip + 2L
    } else if (op == 4L) { # output
      val <- get_val(op_codes[ip + 1L], modes[1])
      append_out(val)
      if (verbose) cat(val, "\n")
      ip <- ip + 2L
    } else if (op == 5L) { # jump-if-true
      a <- get_val(op_codes[ip + 1L], modes[1L])
      b <- get_val(op_codes[ip + 2L], modes[2L])
      if (a != 0L) {
        ip <- b + 1L
      } else {
        ip <- ip + 3L
      }
    } else if (op == 6L) { # jump-if-false
      a <- get_val(op_codes[ip + 1L], modes[1L])
      b <- get_val(op_codes[ip + 2L], modes[2L])
      if (a == 0L) {
        ip <- b + 1L
      } else {
        ip <- ip + 3L
      }
    } else if (op == 7L) { # less than
      a <- get_val(op_codes[ip + 1L], modes[1L])
      b <- get_val(op_codes[ip + 2L], modes[2L])
      addr <- get_addr(op_codes[ip + 3L], modes[3L])
      grow_memory(addr)
      op_codes[addr] <- as.numeric(a < b)
      ip <- ip + 4L
    } else if (op == 8L) { # equals
      a <- get_val(op_codes[ip + 1L], modes[1L])
      b <- get_val(op_codes[ip + 2L], modes[2L])
      addr <- get_addr(op_codes[ip + 3L], modes[3L])
      grow_memory(addr)
      op_codes[addr] <- as.numeric(a == b)
      ip <- ip + 4L
    } else if (op == 9L) { # adjust relative base
      a <- get_val(op_codes[ip + 1L], modes[1L])
      rel_base <- rel_base + a
      ip <- ip + 2L
    } else if (op == 99L) { # halt
      halt <- TRUE
    } else {
      stop("Unknown opcode ", op)
    }
  }
  out_buffer[1:out_len]
}

encode_input <- function(springscript) {
  paste(springscript, collapse = "\n") %>% 
    paste0("\nWALK\n") %>% 
    charToRaw() %>% 
    as.integer()
}

decode_output <- function(out) {
  intToUtf8(out)
}

map_surface <- function(springscript, program = puzzle_data) {
  res <- parse_op_codes_fast(program, encode_input(springscript))
  cat(decode_output(res))
}

map_surface(c(
  "OR D J",
  "NOT C T",
  "AND T J",
  "NOT C T",
  "OR T J",
  "NOT B T",
  "AND T J",
  "AND D J",
  "NOT A T",
  "OR T J"
), puzzle_data)


#####..#.######## NOT A J
#####...######### NOT B J
#####.########### NOT D J
#####.#..########

```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

```{r get-solution-2}
print.beam <- function(x) {
  apply(x, 1, paste, collapse = "") %>% 
    paste(collapse = "\n") %>% 
    cat()
  invisible(x)
}
make_grid <- function(rows, cols, op_codes = puzzle_data) {
  grid <- matrix(".", diff(range(rows)) + 1L, diff(range(cols)) + 1L)
  for (i in rows[1L]:rows[2L]) {
    for (j in cols[1L]:cols[2L]) {
      grid[i - rows[1L] + 1L, j - cols[1L] + 1L] <- if_else(do_scan(j, i, op_codes) == 1, "#", ".")
    }
  }
  class(grid) <- "beam"
  grid
}

find_parking_slot <- function(pre_scan, op_codes = puzzle_data, size = 100L) {
  get_max_width <- function(row) {
    idx <- seq(row, length.out = size)
    max_left <- max(limits[idx, "left"])
    min_right <- min(limits[idx, "right"])
    list(width = min_right - max_left + 1L, left = max_left)
  }
  get_new_limits <- function(n, last_limit) {
    left <- last_limit[1L]
    right <- last_limit[2L]
    while (!do_scan(left, n, op_codes)) {
      left <- left + 1L
    }
    
    if (right < left) {
      right <- left
    }
    while(do_scan(right + 1L, n, op_codes)) {
      right <- right + 1L
    }
    c(left, right)
  }
  limits_grow_rate <- 2048L
  limits <- pre_scan %>% 
    apply(1, function(r) {
      if(!any(r == "#")) {
        rep(NA_integer_, 2L)
      } else {
        range(which(r == "#") - 1L)
      }
    }) %>% 
    t() %>% 
    set_colnames(c("left", "right"))
  row <- 1L
  n <- nrow(pre_scan) + 1L
  limits <- rbind(
    limits,
    matrix(NA_integer_, limits_grow_rate - nrow(limits), 2L)
  )
  while (TRUE) {
    if (n > size) {
      width <- get_max_width(row)
      if (!is.na(width$width) && width$width >= size) {
        return((row - 1L) + 10000L * width$left)
      }
      row <- row + 1L
    }
    last_limit <- limits[n - 1L, ]
    limits[n, ] <- get_new_limits(n - 1L, last_limit)
    n <- n + 1L
    if (n > nrow(limits)) {
      limits <- rbind(
        limits,
        matrix(NA_integer_, limits_grow_rate, 2L)
      )
    }
  }
}

find_parking_slot(scan, puzzle_data, 100L)
```

