---
params:
   task_nr: 18
   year: 2018
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```

```{js cpp-highlighter, file = "Prism_CPP.js", echo = FALSE}
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, fig.align = "center",
  dev.args = list(bg = "transparent")
)
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
library(tidyr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(
  base_url,
  session_cookie
) %>%
  content(encoding = "UTF-8") %>%
  xml_find_all("///article") %>%
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>%
      str_split("\n") %>%
      extract2(1L) %>%
      keep(nzchar)
  }
  text_block %>%
    str_split("") %>%
    do.call(rbind, .)
}

puzzle_data <- local({
  GET(
    paste0(base_url, "/input"),
    session_cookie
  ) %>%
    content(encoding = "UTF-8") %>%
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- matrix(
  c(
    ".", ".", ".", ".", "#", ".", ".", "|", "|", ".",
    "#", ".", "|", ".", ".", ".", "|", "|", ".", ".",
    ".", ".", ".", "|", "#", ".", ".", ".", "|", ".",
    "#", ".", ".", "#", "|", "#", ".", ".", "|", "#",
    ".", ".", "|", ".", "|", ".", ".", ".", "|", ".",
    ".", "#", ".", ".", "|", "|", ".", "#", "|", "|",
    ".", "|", ".", ".", "#", "|", "|", "|", ".", ".",
    "|", "#", ".", ".", "|", ".", ".", ".", ".", ".",
    "#", "#", "#", ".", "#", ".", ".", "#", "|", "|",
    ".", "|", ".", "#", "|", ".", ".", "|", ".", "."
  ),
  10L, 10L
)
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We implement the first part in `R` which - given the small numbers is feasible.

```{r get-solution-1}
count_non_empty <- function(n, acre = puzzle_data) {
  dirs <- rbind(
    c(-1L, -1L),
    c(-1L, 0L),
    c(-1L, 1L),
    c(0L, -1L),
    c(0L, 1L),
    c(1L, -1L),
    c(1L, 0L),
    c(1L, 1L)
  )

  get_neighbors <- function(pos) {
    nbs <- t(t(dirs) + c(pos))
    nbs[between(nbs[, 1L], 1L, nrow(acre)) &
      between(nbs[, 2L], 1L, ncol(acre)), , drop = FALSE]
  }

  change_state <- function(pos) {
    type <- acre[pos]
    nbs <- get_neighbors(pos)
    if (type == ".") {
      ## open field
      cnt <- sum(acre[nbs] == "|")
      if_else(cnt >= 3L, "|", ".")
    } else if (type == "|") {
      ## filled with trees
      cnt <- sum(acre[nbs] == "#")
      if_else(cnt >= 3L, "#", "|")
    } else if (type == "#") {
      ## lumberyard
      if_else(sum(acre[nbs] == "#") >= 1 &&
        sum(acre[nbs] == "|") >= 1, "#", ".")
    }
  }

  for (min in 1:n) {
    new <- acre
    for (i in seq_len(nrow(acre))) {
      for (j in seq_len(ncol(acre))) {
        new[i, j] <- change_state(cbind(i, j))
      }
    }
    acre <- new
  }
  sum(acre == "|") * sum(acre == "#")
}
count_non_empty(10, puzzle_data)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

For the second part we re-implement the algorithm in C++ to be faster. We use a hash to 
detect the cycle and once we detect it we fast forward.

```{Rcpp cpp-algorithm, file = "trees.cpp", cache = TRUE}
```

```{r get-solution-2}
count_non_empty_fast(1000000000, puzzle_data)
```
