---
params:
   task_nr: 7
   year: 2017
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
library(igraph)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_extract_all("[0-9a-z]+") %>% 
    lapply(\(r) list(name = r[1L], weight = as.integer(r[2L]),
                     load = as.list(tail(r, -2L))))
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- c(0L, 2L, 7L, 0L)
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We solve this by constructing a graph. As the graph is a tree, we siply need to return
the name of the root.


```{r get-solution-1}
construct_graph <- function(node_list) {
  vertices <- node_list %>% 
    map(~ tibble(name = .x$name, weight = .x$weight)) %>% 
    bind_rows()
  edges <- keep(node_list, \(n) length(n$load) > 0L) %>% 
    map(~ tibble(from = .x$name, to = unlist(.x$load))) %>% 
    bind_rows()
  G <- graph_from_data_frame(edges, vertices = vertices)
  G %>% 
    set_graph_attr(name = "layout", value = layout_as_tree(G))
}

get_root <- function(G) {
  deg <- degree(G, mode = "in")
  names(deg[deg == 0])
}

G <- construct_graph(puzzle_data)
get_root(G)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

We need to recurse the tree, store the weight of each subtree and once done, we can find 
the node where we have an unbalance.

```{r get-solution-2}
aggregate_weights <- function(G) {
  idx <- dfs(G, get_root(G), order.out = TRUE)$order.out
  for (v in idx) {
    V(G)[v]$cum_weight <- V(G)[v]$weight + 
      sum(neighbors(G, v, "out")$cum_weight)
  }
  G
}

fix_weight <- function(G) {
  ## need to store nbs upfront because calls to igraph functions within 
  ## callbacks lead to a segfault
  nbs <- map(V(G), ~ neighbors(G, .x, "out"))
  is_disbalanced <- function(G, data, extra) {
    nbs[[data["vid"]]]$cum_weight %>% 
      unique() %>% 
      length() %>% 
      is_greater_than(1L)
    
  }
  idx <- dfs(G, get_root(G), order.out = TRUE, out.callback = is_disbalanced) 
  bad_node <- tail(idx$order.out, 1L)
  ## find out which of its children has the wrong weight
  children <- neighbors(G, bad_node, "out")
  cwts <- children$cum_weight
  weights_dist <- table(cwts)
  ## there is a nasty bug in igraph (I guess related to dfs with a callback)
  ## which prevents us from saving variables, that is storing any of the
  ## repeated calls below in a variable does not work (R complains that
  ## it cannot find the variable even if we have defined it, I mean WTF??!?)
  ## formula should read as:
  ##       weight_of_bad_child + right_weight - wrong_weight
  (children[cwts == weights_dist[weights_dist == 1L] %>% 
              names() %>% 
              as.integer()]$weight)  + 
    (setdiff(cwts, weights_dist[weights_dist == 1L] %>% 
               names() %>% as.integer()) %>% 
       unique()) - 
    (weights_dist[weights_dist == 1L] %>% 
       names() %>% as.integer())
}
G <- aggregate_weights(G)
fix_weight(G)
```
