---
params:
   task_nr: 2
   year: 2016
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   force_year <- "2016"
   
   year <- dplyr::coalesce(force_year, format(Sys.Date(), "%Y"))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_split("")
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- parse_puzzle_data()
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We follow the instructions to get to the correct number.

```{r get-solution-1}
get_code <- function(start, ops, key_pad) {
  dirs <- matrix(c(0L, 0L, 1L, -1L, 1L, -1L, 0L, 0L), ncol = 2) %>% 
    set_rownames(c("R", "L", "D", "U"))
  
  move <- function(pos, dir, dirs, key_pad) {
    new_pos <- pos + dirs[dir, ] %>% 
      matrix(ncol = 2L)
    check <- inner_join(
      key_pad, 
      as_tibble(new_pos),
      c("row", "col")
    )
    if (nrow(check) == 0L) {
      pos
    } else {
      new_pos
    }
  }
  start <- key_pad %>% 
    filter(number == start) %>% 
    select(-number) %>% 
    as.matrix()
  pos <- accumulate(ops, ~ reduce(.y, move, .init = .x, dirs = dirs, key_pad = key_pad), 
                    .init = start, dirs = dirs, key_pad = key_pad) %>% 
    set_colnames(c("row", "col")) %>% 
    tail(-1L) %>% 
    as_tibble()
  pos %>% 
    inner_join(key_pad, by = c("row", "col")) %>% 
    pull(number) %>% 
    paste(collapse = "")
}

key_pad  <- expand.grid(col = -1:1, row = -1:1) %>%
    select(2:1) %>% 
    mutate(number = rownames(.) %>% as.integer()) %>% 
    as_tibble()

get_code(5, puzzle_data, key_pad)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

We need to define a different key pad design and apply the function to this design.

```{r get-solution-2}
star_pad <- expand.grid(col = -2:2,
                        row = -2:2) %>% 
  select(2:1) %>% 
  mutate(number = c(NA_character_, NA_character_, "1", NA_character_, NA_character_,
                    NA_character_, "2", "3", "4", NA_character_,
                    "5", "6", "7", "8", "9",
                    NA_character_, "A", "B", "C", NA_character_,
                    NA_character_, NA_character_, "D", NA_character_, NA_character_)) %>% 
  filter(!is.na(number)) %>% 
  as_tibble()
get_code(5, puzzle_data, star_pad)
```
