---
params:
   task_nr: 12
   year: 2018
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  start <- text_block[[1L]] %>% 
    str_extract("[.#]+") %>% 
    unlist()
  rules <- text_block %>% 
    str_detect(fixed("=>"))
  rules <- text_block[rules] %>% 
    str_split(fixed(" => ")) %>% 
    map(~ set_names(.x[2L], .x[1L])) %>% 
    flatten_chr()
  
  list(start = start, rules = rules)
               
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- parse_puzzle_data()
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution


```{r min-entropy, cache = TRUE}
p <- c(".", "#")

ar <- rep(".", 32) %>% 
  set_names(expand.grid(p,p,p,p,p) %>%
  apply(1, paste, collapse = ""))
r <- c(example_data$rules, ar[!names(ar) %in% names(example_data$rules)])

grow_plants <- function(n, start = puzzle_data$start, rules = puzzle_data$rules) {
  first_pot <- 0
  for (i in seq_len(n)) {
    start <- paste0("...", start, "...")
    new_gen <- ""
    for (j in 3:(nchar(start) - 2L)) {
      token <- str_sub(start, j - 2, j + 2L)
      if (!token %in% names(rules)) {
        new_gen <- paste0(new_gen, ".")
      } else {
        new_gen <- paste0(new_gen, rules[token])
      }
    }
    head <- str_sub(new_gen, 1L, 1L + abs(first_pot)) %>% 
      str_remove("^\\.*") %>% 
      extract2(1L)
    rex <- paste0("^\\.{1,", 1L + abs(first_pot), "}|\\.*$")
    start <- str_remove_all(new_gen, rex) %>% 
      extract2(1L)
    first_pot <- -nchar(head)
  }
  cat(start, "\tOffset:", first_pot, "\n")
  start %>% 
    str_split("") %>% 
    extract2(1L) %>% 
    equals("#") %>% 
    which() %>% 
    add(first_pot - 1L) %>% 
    sum()
}
grow_plants(20)
grow_plants(50000000000)

grow_plants(2, example_data$start, example_data$rules)

```

```{r get-solution-1, comment=""}
as.matrix.elve_msg <- function(x, n = 0L, border = 6L, fill = c(0L, 1L)) {
  coords <- move_stars(x, n)
  ## need to flip because x coordinates correspond to columns
  coords <- coords[, 2:1]
  min_x <- apply(coords, 2, min)
  cnt <- sweep(coords, 2, min_x, "-") + 1
  maxs <- apply(cnt, 2, max)
  mat <- matrix(fill[1L], maxs[1L] + border, maxs[2L] + border)
  mat[cnt + border / 2] <- fill[2L]
  mat
}

plot.elve_msg <- function(x, n = 0L) {
  mat <- as.matrix(x, n) %>% 
    t()
  par(mar = rep(0, 4L))
  image(mat[, ncol(mat):1], col = c("transparent", "black"), axes = FALSE, asp = 1)
}

print.elve_msg <- function(x, n = 0L) {
  mat <- as.matrix(x, n, border = 4L, fill = c(".", "#"))
  apply(mat, 1, paste, collapse = "") %>% 
    paste(collapse = "\n") %>% 
    cat()
}
print(puzzle_data, min_entropy)
plot(puzzle_data, min_entropy)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

The seconds are exactly the minimum entropy we calculated earlier.

```{r get-solution-2}
min_entropy
```
