---
params:
   task_nr: 5
   year: 2019
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_split(",") %>% 
    do.call(c, .) %>% 
    as.integer()
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We include the parameter mode and the new op codes into the parser (and also include the
op codes for the second part of the puzzle).

```{r get-solution-1}
split_digits <- function(n) {
  i <- floor(log10(n)) + 1L
  digits <- integer(i)
  while (n > 0) {
    digits[i] <- n %% 10L
    n <- n %/% 10L
    i <- i - 1L
  }
  digits
}

parse_op_codes <- function(op_codes = puzzle_data, input = 1L, verbose = FALSE) {
  out_buffer <- integer(0L)
  add <- function(x, y, res, modes) {
    if (modes[1L] == 0L) {
      x <- op_codes[x + 1L]
    }
    if (modes[2L] == 0L) {
      y <- op_codes[y + 1L]
    }
    op_codes[[res + 1L]] <<- x + y
    ip <<- ip + 4L
  }
  mul <- function(x, y, res, modes) {
    if (modes[1L] == 0L) {
      x <- op_codes[x + 1L]
    }
    if (modes[2L] == 0L) {
      y <- op_codes[y + 1L]
    }
    op_codes[[res + 1L]] <<- x * y
    ip <<- ip + 4L
  }
  set <- function(res, ..., modes) {
    op_codes[[res + 1L]] <<- input
    ip <<- ip + 2L
  }
  out <- function(x, ..., modes) {
    if (modes[1L] == 0L) {
      x <- op_codes[x + 1L]
    }
    out_buffer <<- c(out_buffer, x)
    if (verbose) {
      cat(x, "\n")
    }
    ip <<- ip + 2L
  }
  jnz <- function(x, y, ..., modes) {
    if (modes[1L] == 0L) {
      x <- op_codes[x + 1L]
    }
    if (modes[2L] == 0L) {
      y <- op_codes[y + 1L]
    }
    if (x != 0L) {
      ip <<- y + 1L  
    } else {
      ip <<- ip + 3L
    }
  }
  jeqz <- function(x, y, ..., modes) {
    if (modes[1L] == 0L) {
      x <- op_codes[x + 1L]
    }
    if (modes[2L] == 0L) {
      y <- op_codes[y + 1L]
    }
    if (x == 0L) {
      ip <<- y + 1L  
    } else {
      ip <<- ip + 3L
    }
  }
  lt <- function(x, y, res, modes) {
    if (modes[1L] == 0L) {
      x <- op_codes[x + 1L]
    }
    if (modes[2L] == 0L) {
      y <- op_codes[y + 1L]
    }
    op_codes[[res + 1L]] <<- (x < y)
    ip <<- ip + 4L
  }
  
  eq <- function(x, y, res, modes) {
    if (modes[1L] == 0L) {
      x <- op_codes[x + 1L]
    }
    if (modes[2L] == 0L) {
      y <- op_codes[y + 1L]
    }
    op_codes[[res + 1L]] <<- (x == y)
    ip <<- ip + 4L
  }
  
  funs <- list(add, mul, set, out, jnz, jeqz, lt, eq)
  get_op <- function(op_code) {
    digits <- split_digits(op_code)
    n <- length(digits)
    digits <- c(rep(0L, 5L), digits)[seq(n + 1L, length.out = 5L)]
    list(op = sum(digits[5:4] * 10L ^ (0:1)),
         modes = digits[3:1])
  }
  ip <- 1L
  n <- length(op_codes)
  op <- get_op(op_codes[ip])
  while(ip <= n && op$op %in% seq_along(funs)) {
    args <- as.list(op_codes[seq(ip + 1L, length.out = 3L)])
    do.call(funs[[op$op]], c(args, modes = list(op$modes)))
    op <- get_op(op_codes[ip])
  }
  tail(out_buffer, 1L)
}

parse_op_codes(puzzle_data, 1L)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

We use a differnt starting value this time to get the result. 

```{r get-solution-2}
parse_op_codes(puzzle_data, 5L)
```
