---
params:
   task_nr: 11
   year: 2016
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   force_year <- "2016"
   
   year <- dplyr::coalesce(force_year, format(Sys.Date(), "%Y"))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_remove_all("-compatible") %>% 
    str_extract_all("\\S+ (microchip|generator)") %>% 
    set_names(paste0("F", 1:4))
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

```{r get-solution-1}
is_compatible <- function(chip, gen, floors, current_floor) {
  chip_type <- str_remove(chip, " .*$")
  gen_type <- str_remove(gen, " .*$")
  if (is.na(chip)) {
    if (is.na(gen)) {
      FALSE
    } else {
      setdiff(floors[[current_floor]], gen)
    }
    
  } && is.na(gen)) {
    FALSE
  } 
}

generate_candidates <- function(chips, gens, floors, current_floor) {
  cands <- tibble(e1 = character(0L), e2 = character(0L), floor = integer(0L))
  for (chip in c(NA_character_, chips)) {
    for (gen in c(NA_character_, gens)) {
      if (is_compatible(chip, gen, floors, current_floor)) {
        floors <- get_valid_floors(chip, gen, floors, current_floor)
        if (length(floors) > 0L) {
          cands <- rows_append(cands, tibble(e1 = chip, e2 = gen, floor = floors))
        }
      }
    }
  }
  cands
}

count_moves <- function(floors, current_floor) {
  if (all(lengths(floors[1:3]) == 0L)) {
    ## floors 1 - 3 are empty (i.e. everything is in floor 4) 
    return(0)
  }
  chips <- str_subset(floors[[current_floor]], fixed("microchip"))
  gens <-  str_subset(floors[[current_floor]], fixed("generator"))
  cand <- generate_candidates(chips, gens, floors, current_floor)
}
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

```{r get-solution-2}
```
