---
params:
   task_nr: 3
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   o_file <- sprintf("%s_%s", format(Sys.Date(), "%Y"), 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
width: 100%;
}

.back {
font-size: 2rem;
}

.day-desc {
border: 2px dotted;
border-radius: 6px;
border-color: var(--blockquote-border-color);
padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center")
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/2024/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8")
})
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We can use *regex*  to extract all valid `mul` statements:

```{r get-solution-1}
puzzle_data %>% 
  str_extract_all("mul\\(\\d+,\\d+\\)") %>% 
  extract2(1L) %>% 
  str_extract_all("\\d+") %>% 
  vapply(\(x) prod(as.integer(x)), numeric(1L)) %>% 
  sum()
```


## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

We use *regex* again to extract the conditionals too. Then, we discard `mul` operations 
which are preceded by a `don't` conditional:

```{r get-solution-2}
instructions <- puzzle_data %>% 
  str_extract_all("mul\\(\\d+,\\d+\\)|do\\(\\)|don't\\(\\)") %>% 
  extract2(1L)

skip_start<- str_which(instructions, fixed("don't()"))
skip_end <- str_which(instructions, fixed("do()"))

bad <- reduce(skip_end, function(solution, end) {
  start <- solution$candidates
  res <- end
  idx <- start < end
  if (length(start[idx]) > 0L) {
    res <- min(start[idx]):end  
  }
  list(candidates = start[!idx], res = c(solution$res, res))
},
.init = list(candidates = skip_start, res = NULL)) %>% 
  extract2("res")

instructions[-bad] %>% 
  str_extract_all("\\d+") %>% 
  vapply(\(x) prod(as.integer(x)), numeric(1L)) %>% 
  sum()
```
