---
params:
   task_nr: 16
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   o_file <- sprintf("%s_%s", format(Sys.Date(), "%Y"), 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
library(knitr)
library(cli)
library(bit64)
library(ggplot2)
library(igraph)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/2024/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) > 1L) {
    text_block <- text_block %>% 
      paste(collapse = "\n")
  }
  text_block %>% 
    str_split("\n") %>% 
    extract2(1L) %>% 
    keep(nzchar) %>% 
    str_split("") %>% 
    do.call(rbind, .)
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r get_example_data, eval = interactive(), echo = FALSE}
example_data <- parse_puzzle_data()
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

```{r get-solution-1}
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution


```{r get-solution-2}
construct_graph <- function(reindeer_map) {
  dd <- dim(reindeer_map)
  dirs <- rbind(
      cbind(-1L, 0L),
      cbind(0L, 1L),
      cbind(1L, 0L),
      cbind(0L, -1L)
    ) %>% 
      set_rownames(c("^", ">", "v", "<"))
  turn <- function(dir, clockwise) {
    if (clockwise) {
      switch(dir,
             "^" = ">",
             ">" = "v",
             "v" = "<",
             "<" = "^")
    } else {
      switch(dir,
             "^" = "<",
             ">" = "^",
             "v" = ">",
             "<" = "v")
    }
  }
  
  make_vertex_id <- function(current_pos, current_dir) {
    paste(current_pos, collapse = "/") %>% 
      paste(current_dir, sep = "/")
  }
  
  create_vertex <- function(current_pos, current_dir) {
    id <- make_vertex_id(current_pos, current_dir)
    if (!id %in% V(G)$name) {
      G <<- G %>% 
        add_vertices(1L, name = id)
    }
    id
  }
  
  is_valid_pos <- function(new_pos) {
    all(new_pos >= c(1L, 1L) & new_pos <= dd) &&
      reindeer_map[matrix(new_pos, nrow = 1)] != "#" 
  }
  
  get_neighbor_nodes <- function(current_pos) {
    nbs <- t(t(dirs) + c(current_pos))
    nbs[apply(nbs, 1, is_valid_pos), , drop = FALSE]
  }
  
  get_edges <- function() {
    edges <- tibble(from = character(0L), 
                    to = character(0L),
                    weight = integer(0L))
    no_walls <- which(reindeer_map != "#", arr.ind = TRUE)
    for (row in seq_len(nrow(no_walls))) {
      current_node <- no_walls[row, , drop = FALSE]
      nbs <- get_neighbor_nodes(current_node)
      nb_dirs <- rownames(nbs)
      for (dir in nb_dirs) {
        nb <- nbs[dir, , drop = FALSE]
        from <- make_vertex_id(current_node, dir)
        to <- make_vertex_id(nb, dir)
        edges <- edges %>% 
          bind_rows(
            tibble(from = from, to = to, weight = 1L)
          )
        if (turn(dir, TRUE) %in% nb_dirs) {
          edges <- edges %>% 
            bind_rows(
              tibble(from = from, to = make_vertex_id(current_node, turn(dir, TRUE)), 
                     weight = 1000L)
            )
        } else if (turn(dir, FALSE) %in% nb_dirs) {
          edges <- edges %>% 
            bind_rows(
              tibble(from = from, to = make_vertex_id(current_node, turn(dir, FALSE)), 
                     weight = 1000L)
            )
        }
      }
    }
  edges
  }
  edges <- get_edges()
  list(G = graph_from_data_frame(edges, directed = TRUE), edges = edges)
}
vn <- NULL
res <- construct_graph(example_data)

goal <- "8/12/v"
distances(res$G, "14/2/>", goal)
shortest_paths(res$G, "14/2/>", goal)$vpath[[1L]]


```


