---
params:
   task_nr: 8
   year: 2023
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: TRUE
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
library(numbers)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L)
  }
  text_block <- text_block[nzchar(text_block)]
  dirs <- text_block[1L] %>% 
    str_split("") %>% 
    extract2(1L)
  edges <- text_block[-1L] %>% 
    str_remove_all("\\(|\\)") %>% 
    str_split(" = |, ")
  nms <- map_chr(edges, 1L)
  edges <- map(edges, ~ list(L = .x[[2L]], R = .x[[3L]])) %>% 
    set_names(nms)
  list(dirs = dirs, edges = edges)
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We use an environment for storing left and right neighbor for fast traversal. We then 
simply  follow the route until the goal.


```{r get-solution-1}
navigate_wasteland <- function(edges, dirs) {
  pos <- "AAA"
  goal <- "ZZZ"
  ptr <- 1L
  cnt <- 0L
  while (pos != goal) {
    cnt <- cnt + 1L
    next_dir <- dirs[ptr]
    pos <- edges[[pos]][[next_dir]]
    ptr <- ptr %% length(dirs) + 1L
  }
  cnt
}

navigate_wasteland(puzzle_data$edges, puzzle_data$dirs)

```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution


```{r get-solution-2}
navigate_wasteland_ghosts <- function(edges, dirs) {
  nodes <- ls(edges)
  goals <- nodes[str_sub(nodes, -1L) == "Z"]
  pos <- nodes[str_sub(nodes, -1L) == "A"]
  path_len <- rep(0L, length(pos))
  is_active <- rep(TRUE, length(pos))
  ptr <- 1L
  while (any(is_active)) {
    next_dir <- dirs[ptr]
    for (i in seq_along(pos)) {
      if (!is_active[i]) {
        next
      }
      nb <- edges[[pos[[i]]]][[next_dir]]
      pos[[i]] <- nb
      path_len[[i]] <- path_len[[i]] + 1L
      if (nb %in% goals) {
        is_active[i] <- FALSE
      }
    }
    ptr <- ptr %% length(dirs) + 1L
  }
  path_len %>% 
    reduce(LCM) %>%
    print(digits = 9L)
}


navigate_wasteland_ghosts(puzzle_data$edges, puzzle_data$dirs)

```
