---
params:
   task_nr: 5
   year: 2025
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L)
  }
  text_block <- text_block[nzchar(text_block)]
  fresh <- str_detect(text_block, fixed("-"))
  ranges <- text_block[fresh] %>% 
    str_split("-") %>% 
    do.call(rbind, .)
  storage.mode(ranges) <- "numeric"
  ing <- text_block[!fresh][-1L] %>% 
    str_extract_all("\\d+")
  storage.mode(ing) <- "numeric"
  list(fresh = ranges, ingredients = ing)
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We loop over all ingredients and check for each freh range whether falls wihtin.

```{r get-solution-1}
count_fresh_ingredients <- function(inventory) {
  ingredients <- inventory$ingredients
  ranges <- inventory$fresh
  cnt <- 0L
  for (ingredient in ingredients) {
    if (any(ingredient >= ranges[, 1L] & ingredient <= ranges[, 2L])) {
      cnt <- cnt + 1L
    }
  }
  cnt
}

count_fresh_ingredients(puzzle_data)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

For the second part we iterate over all intervls and merge them if they overlap. 
Eventually we sum their ranges.

```{r get-solution-2}
count_all_fresh_ingredients <- function(inventory) {
  ranges <- inventory$fresh
  ranges <- ranges[order(ranges[, 1L], ranges[, 2L]), , drop = FALSE]
  disjoint <- list(ranges[1L, ])
  for (i in 2:nrow(ranges)) {
    new_range <- ranges[i, ]
    for (rng_i in seq_along(disjoint)) {
      rng <- disjoint[[rng_i]]
      if (new_range[2L] < rng[1L] - 1L || rng[2L] + 1L < new_range[1L]) {
        ## no join => continue
        next
      }
      disjoint <- disjoint[-rng_i]
      new_range <- c(min(new_range[1L], rng[1L]), max(new_range[2L], rng[2L]))
      break
    }
    disjoint <- c(disjoint, list(new_range))
  }
  map_dbl(disjoint, ~ diff(.x) + 1) %>% 
    sum()
}
count_all_fresh_ingredients(puzzle_data) %>% 
  print(digit = 12)
```
