---
params:
   task_nr: 10
   year: 2017
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_split(",") %>% 
    extract2(1L) %>% 
    as.integer()
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We solution can be translated directly into an `R` code. To recycle indices,w e have to 
use some modulo arithmetic.

```{r get-solution-1}
knot_hash <- function(lengths, n = 256) {
  stream <- seq(0L, n - 1L)
  pos <- 1L
  skip_size <- 0L
  for (l in lengths) {
    idx <- (seq(pos, by = 1L, length.out = l) - 1L) %% n + 1L
    stream[idx] <- rev(stream[idx])
    pos <- (pos + l + skip_size - 1L) %% n + 1L
    skip_size <- skip_size + 1L
  }
  prod(stream[1:2])
}

knot_hash(puzzle_data)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

To test the test cases we add a flag `convert` to avoid translating the input back 
into the comma separted form.


```{r get-solution-2}
knot_hash_improved <- function(lengths, convert = TRUE) {
  n <- 256L
  if (convert) {
    lengths <- paste(lengths, collapse = ",")
  } 
  n_lengths <- lengths %>% 
    utf8ToInt() %>% 
    c(., 17L, 31L, 73L, 47L, 23L)
  stream <- seq(0L, n - 1L)
  pos <- 1L
  skip_size <- 0L
  for (round in 1:64) {
    for (l in n_lengths) {
      idx <- (seq(pos, by = 1L, length.out = l) - 1L) %% n + 1L
      stream[idx] <- rev(stream[idx])
      pos <- (pos + l + skip_size - 1L) %% n + 1L
      skip_size <- skip_size + 1L
    }
  }
  m <- matrix(stream, 16L, 16L)
  apply(m, 2L, function(col) {
    Reduce(bitwXor, col)
  }) %>% 
    as.hexmode() %>% 
    format(2L) %>% 
    paste(collapse = "")
}

knot_hash_improved(puzzle_data)
```
