---
title: '`r paste("<span>Task 3 <span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "2021-12-4"
knit: (function(inputFile, encoding) {
   year <- format(Sys.Date(), "%Y");
   o_file <- sprintf("%s_%s", year, tools::file_path_sans_ext(basename(inputFile)));
   day <- as.numeric(gsub(".*(\\d+)$", "\\1", o_file));
   rm <- readLines(here::here("README.md"));
   line <- grep(paste0("Day ", day, "([^0-9]?$|\\])"), rm);
   rm[line] <- sprintf("- [x] [Day %i](https://thothal.github.io/AoC/%s.html)", day, o_file);
   cat(rm, file = here::here("README.md"), sep = "\n");
   index <- readLines(here::here("index.Rmd"));
   
   if (!any(grepl(paste0(o_file, ".html"), index, fixed = TRUE))) {
      rx <- if (day > 1) sprintf("%s_task%i.html", year, day - 1) else sprintf("# %s", year);
      line <- grep(rx, index, fixed = TRUE);
      new_line <- sprintf("* [Task %i](%s.html)", day, o_file);
      
      if (day == 1) {
         new_line <- c("", new_line);
      }
      

      index <- c(index[seq(1, line)], new_line, if(line < length(index)) index[(line + 1):length(index)]);
      cat(index, file = here::here("index.Rmd"), sep = "\n");
      rmarkdown::render(here::here("index.Rmd"), encoding = encoding, output_file = here::here("docs", "index"));
      
   }
   
   rmarkdown::render(inputFile, encoding = encoding, output_file = o_file, output_dir = here::here("docs")) })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center")
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

First we need to load the required libraries. 

```{r libs, warning = FALSE}
library(httr)
library(magrittr)
library(tibble)
library(dplyr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache=FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
puzzle_3 <- GET("https://adventofcode.com/2021/day/3",
                session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

data_3 <- GET("https://adventofcode.com/2021/day/3/input",
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  read.table(text = .) %>% 
  as_tibble() %>% 
  set_names("status_code")
```

# Puzzle Day 3

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle_3[[1]])
```

### Solution


```{r solution-a}
data_3

```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle_3) > 1}
cat(puzzle_3[[2]])
```

### Solution


```{r solution-b, eval = length(puzzle_3) > 1}
data_3 
```


