---
params:
   task_nr: 1
   year: 2016
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   force_year <- "2016"
   
   year <- dplyr::coalesce(force_year, format(Sys.Date(), "%Y"))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_split(", ?") %>% 
    extract2(1L)
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

First, we calculate the endpoint, then we calculate the manhatten distance to get the 
result.

```{r get-solution-1}
get_path <- function(ops) {
  accumulate(ops, function(pos, op) {
    op <- str_extract_all(op, "[LR]|\\d+") %>% 
      extract2(1L)
    new_dir <- case_when(
      pos$dir == "N" ~ if_else(op[1L] == "L", "W", "E"),
      pos$dir == "E" ~ if_else(op[1L] == "L", "N", "S"),
      pos$dir == "S" ~ if_else(op[1L] == "L", "E", "W"),
      pos$dir == "W" ~ if_else(op[1L] == "L", "S", "N")
    )
    new_pos <- list(
      N = c(0L, -1L),
      E = c(1L, 0L),
      S = c(0L, 1L),
      W = c(-1L, 0L)
    )[[new_dir]] * as.integer(op[2L]) + pos$pos
    list(dir = new_dir, pos = new_pos)
  }, .init = list(dir = "N", pos = c(0L, 0L)))
}

path <- get_path(puzzle_data)
sum(abs(tail(path, 1L)[[1L]]$pos))
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

We simply look at all the positions, fill in the intermediate steps and check which point 
was visited twice first.

```{r get-solution-2}
get_intermediate_steps <- function(all_pos) {
  intermediate_pos <- matrix(0, 0L, 2L)
  for (i in 1:(nrow(all_pos) - 1L)) {
    start <- all_pos[i, ]
    end <- all_pos[i + 1L,]
    if (start[1L] == end[1L]) {
      intermediate_pos <- rbind(intermediate_pos,
                                cbind(start[1L], start[2L]:end[2L]))
    } else {
      intermediate_pos <- rbind(intermediate_pos,
                                cbind(start[1L]:end[1L], start[2L]))
    }
    # Remove end point as it will be included in the next iteration
    intermediate_pos <- intermediate_pos %>% 
      head(-1L)
  }
  intermediate_pos
}

get_first_duplicated <- function(path) {
  all_pos <- map(path, "pos") %>% 
    do.call(rbind, .) 
  int_pos <- get_intermediate_steps(all_pos)
  idx <- int_pos %>% 
    duplicated() %>% 
    which() %>% 
    min()
  int_pos[idx, ]
}

sum(abs(get_first_duplicated(path)))
```
