---
params:
   task_nr: 21
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   force_year <- "2024"
   
   
   o_file <- sprintf("%s_%s", year, 
   })
   year <- dplyr::coalesce(force_year, format(Sys.Date(), "%Y"))
                     
                     tools::file_path_sans_ext(basename(inputFile)))
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
library(stringi)
library(knitr)
library(cli)
library(bit64)
library(igraph)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/2024/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_split("")
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- parse_puzzle_data()
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution


```{r get-solution-1}
make_numeric_pad <- function() {
  G <- make_lattice(c(3L, 4L))
  V(G)$name <- c("--", "0", "A", 1:9)
  V(G)$start <- FALSE
  V(G)[name == "A"]$start <- TRUE
  V(G)$shape <- "square"
  V(G)$color <- "lightgray"
  V(G)$size <- 50
  G %>% 
    set_graph_attr("layout", layout_on_grid(G, width = 3L, height = 4L))
}

make_click_dict <- function(G) {
  map(V(G)$name, function(from) {
    path <- all_shortest_paths(G, from, V(G))$res
    end <- vapply(path, function(p) tail(p, 1L)$name, character(1L))
    tibble(from = from, to = end, path = path)
  }) %>% 
    list_rbind() %>% 
    filter(from != to)
}

get_click_sequence <- function(code, dict) {
  get_next_part <- function(start, end) {
    if (is.null(end)) {
      res <- NULL
    } else {
      paths <- dict %>% 
        filter(from == start, to == end) %>% 
        pull(path)
      
    }
  }
}
num_pad <- make_numeric_pad()
click_dict <- make_click_dict (num_pad)
get_click_sequence(G)
plot(
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution


```{r get-solution-2}

```

