---
params:
   task_nr: 12
   year: 2020
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
    str_extract_all("[NSEWLRF]|-?\\d+") %>% 
    do.call(rbind, .) %>% 
    set_colnames(c("action", "val")) %>% 
    as_tibble() %>% 
    mutate(val = as.integer(val))
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We simulate the process by iterating over the instructions.

```{r get-solution-1}
navigate_ship <- function(navigation) {
  n <- nrow(navigation) 
  pos <- c(0, 0)
  dirs <- c("N", "E", "S", "W")
  dir <- 2L
  for (idx in seq_len(n)) {
    inst <- navigation %>% 
      slice(idx) %>% 
      as.list()
    if (inst$action %in% c("S", "N")) {
      sign <- if_else(inst$action == "S", -1L, 1L)
      pos[1L] <- pos[1L] + sign * inst$val
    } else if (inst$action %in% c("E", "W")) {
      sign <- if_else(inst$action == "W", -1L, 1L)
      pos[2L] <- pos[2L] + sign * inst$val
    } else if (inst$action %in% c("L", "R")) {
      sign <- if_else(inst$action == "L", -1L, 1L)
      turns <- inst$val %/% 90L * sign
      dir <- (dir - 1L + turns) %% 4L + 1L
    } else if (inst$action == "F") {
      if (dir %in% c(1, 3)) {
        sign <- if_else(dir == 3L, -1L, 1L)
        pos[1L] <- pos[1L] + sign * inst$val
      } else {
        sign <- if_else(dir == 4L, -1L, 1L)
        pos[2L] <- pos[2L] + sign * inst$val
      }
    }
  }
  sum(abs(pos))
}

navigate_ship(puzzle_data)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]] %>% str_replace_all(fixed("*"), "\\*"))
```

### Solution

Instead of moving the ship we move the waypoint now for most of the instructions. The 
general flow remains the same.

```{r get-solution-2}
navigate_ship_by_waypoint <- function(navigation) {
  n <- nrow(navigation) 
  wp <- c(1L, 10L)
  pos <- c(0, 0)
  for (idx in seq_len(n)) {
    inst <- navigation %>% 
      slice(idx) %>% 
      as.list()
    if (inst$action %in% c("S", "N")) {
      sign <- if_else(inst$action == "S", -1L, 1L)
      wp[1L] <- wp[1L] + sign * inst$val
    } else if (inst$action %in% c("E", "W")) {
      sign <- if_else(inst$action == "W", -1L, 1L)
      wp[2L] <- wp[2L] + sign * inst$val
    } else if (inst$action %in% c("L", "R")) {
      sign <- if_else(inst$action == "L", -1L, 1L)
      turns <- ((sign * inst$val) %% 360L) %/% 90L
      wp <- switch(turns + 1L,
                   wp,                 # turns == 0 =>   0째
                   c(-wp[2L], wp[1L]), # turns == 1 =>  90째
                   -wp,                # turns == 2 => 180째
                   c(wp[2L], -wp[1L])) # turns == 3 => 270째
    } else if (inst$action == "F") {
      pos <- pos + inst$val * wp
    }
  }
  sum(abs(pos))
}

navigate_ship_by_waypoint(puzzle_data)
```
