---
params:
   task_nr: 8
   year: 2016
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   force_year <- "2016"
   
   year <- dplyr::coalesce(force_year, format(Sys.Date(), "%Y"))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  rotations <- str_detect(text_block, fixed("rotate"))
  map2(text_block, rotations, function(line, is_rotation) {
    tokens <- line %>% 
      str_extract_all("-?\\d+|row|column") %>% 
      extract2(1L)
    if (is_rotation) {
      tibble(op = "rotate",
             where = tokens[[1L]],
             x = as.integer(tokens[[2L]]),
             y = as.integer(tokens[[3L]]))
    } else {
      tibble(op = "rect",
             where = NA_character_,
             x = as.integer(tokens[[1L]]),
             y = as.integer(tokens[[2L]]))
    }
  }) %>% 
    list_rbind()
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- parse_puzzle_data(
  c("rect 3x2",
    "rotate column x=1 by 1",
    "rotate row y=0 by 4",
    "rotate column x=1 by 1")
)
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We write a function for each the `rect` and the `rotate` operations and loop through all
instructions and apply the respective function.

```{r get-solution-1}
print.screen <- function(x, on = "#", off = ".", ...) {
  x[x == TRUE] <- on
  x[x == FALSE] <- off
  apply(x, 1L, paste, collapse = "") %>% 
    paste(collapse = "\n") %>% 
    cat()
}

rotate <- function(screen, where, x, y) {
  if (where == "column") {
    screen <- t(screen)
  }
  slice <- c(screen[x + 1L, ])    
  rotated <- lag(slice, y)
  rotated[1:y] <- tail(slice, y)
  screen[x + 1L, ] <- rotated
  if (where == "column") {
    screen <- t(screen)
  }
  screen
}

rect <- function(screen, x, y, ...) {
  screen[1:y, 1:x] <- TRUE
  screen
}

make_screen <- function(n, m) {
  matrix(FALSE, n, m) %>% 
    set_class("screen")
}

execute_ops <- function(ops, n = 6L, m = 50L) {
  screen <- make_screen(n, m)
  for (i in 1:nrow(ops)) {
    screen <- ops %>% 
      slice(i) %>%
      rename(name = "op") %>% 
      as.list() %>% 
      c(screen = list(screen)) %>% 
      do.call(call, .) %>% 
      eval()
  }
  screen
}

screen <- execute_ops(puzzle_data, 6L, 50L)

sum(screen)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

```{r get-solution-2, comment = ""}
print(screen, off = " ") # ZFHFSFOGPO
```
