---
params:
   task_nr: 14
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   o_file <- sprintf("%s_%s", format(Sys.Date(), "%Y"), 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
width: 100%;
}

.back {
font-size: 2rem;
}

.day-desc {
border: 2px dotted;
border-radius: 6px;
border-color: var(--blockquote-border-color);
padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center")
## Define a function to write text in typewriter font
tt <- function(x) {
	if (knitr::is_latex_output()) {
		sprintf("\\texttt{%s}", as.character(x))
	} else if (knitr::is_html_output()) {
		sprintf("<tt>%s</tt>", as.character(x))
	} else {
		x
	}
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(tibble)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/2021/day/", params$task_nr)
puzzle <- GET(base_url,
				  session_cookie) %>% 
	content(encoding = "UTF-8") %>% 
	xml_find_all("///article") %>% 
	lapply(as.character)

puzzle_data <- local({
	res <- GET(paste0(base_url, "/input"),
				  session_cookie) %>% 
		content(encoding = "UTF-8") %>% 
		str_split("\n+") %>% 
		`[[`(1L)
	rules <- head(tail(res, -1L), -1L)
	lkp <- str_extract(rules, "^..") %>% 
		set_names(str_extract(rules, ".$"))
	list(start = res[[1L]],
		  rules = lkp)
})
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We split the string in pairs of two and replace matches according to the given
rules. Then we drop the first letter in each pair or tripplet, as it is already
present in the pair or triplet before.

```{r solution-a, cache = FALSE}
insert <- function(base, letter) {
	if (length(base) != length(letter)) browser()
	str_c(str_sub(base, 1L, 1L),
			letter,
			str_sub(base, 2L, 2L))
}

replace_line <- function(n, 
								 str = puzzle_data$start,
								 rules = puzzle_data$rules) {
	wrapper <- function(str, i) {
		idx <- seq(1L, str_length(str) - 1)
		tokens <- str_sub(str, idx, idx + 1)
		mtc <- tokens %in% rules
		tokens[mtc] <- insert(tokens[mtc], names(rules[match(tokens, rules)]))
		tokens[-1L] <- str_sub(tokens[-1L], 2L)
		str_c(tokens, collapse = "")
	}
	all_ltrs <- str_c(rules, collapse = "") %>% 
		str_split("") %>% 
		`[[`(1) %>% 
		unique()
	reduce(seq(1L, n), wrapper, .init = str) %>% 
		str_count(fixed(all_ltrs)) %>% 
		range() %>% 
		diff()
}

replace_line(10)
```


## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

```{r solution-b, eval = length(puzzle) > 1, comment = NA}
library(igraph)
G <- imap_dfr(puzzle_data$rules, function(pair, insert) {
	res <- insert(pair, insert)
	data.frame(from = rep(pair, 2L),
				  to   = c(str_sub(res, 1L, 2L),
				  			str_sub(res, 2L, 3L)))
}) %>% 
	graph_from_data_frame()
```



