---
params:
   task_nr: 8
   year: 2018
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   year <- basename(dirname(dirname(inputFile)))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}

```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  if (length(text_block) == 1L) {
    text_block <- text_block %>% 
      str_split("\n") %>% 
      extract2(1L) %>% 
      keep(nzchar)
  }
  text_block %>% 
   str_split(" ") %>% 
    extract2(1L) %>% 
    as.integer()
}

puzzle_data <- local({
  GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    parse_puzzle_data()
})
```

```{r example-data, eval = interactive(), echo = FALSE}
example_data <- c(2L, 3L, 0L, 3L, 10L, 11L, 12L, 1L, 1L, 0L, 1L, 99L, 2L, 1L, 1L, 2)
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We iterate through the list and generate the nodes recursively

```{r get-solution-1}
construct_tree <- function(node_list = puzzle_data) {
  make_node <- function(start) {
    node_count <- node_list[start]
    meta_count <- node_list[start + 1L]
    pos <- start + 2L
    kids <- NULL
    
    if (node_count > 0L) {
      kids <- vector("list", node_count)
      for (i in seq_len(node_count)) {
        child <- make_node(pos)
        kids[[i]] <- child$node
        pos <- child$pos
      }
    }
    
    meta <- if (meta_count > 0L) {
      node_list[seq(pos, length.out = meta_count)]
    } else {
      NULL
    }
    
    res <- list(
      pos = pos + meta_count,
      node = list(kids = kids, meta = meta)
    )
    return(res)
  }
  make_node(1L)$node
}
tree <- construct_tree(puzzle_data)
tree %>% 
  unlist %>% 
  sum()

```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

We walk through the recursive lists and build the value as requested.

```{r get-solution-2}
score_tree <- function(tree) {
  if (is.null(tree$kids)) {
    res <- sum(tree$meta)
  } else {
    kids_idx <- seq_along(tree$kids)
    res <- 0L
    for (idx in tree$meta) {
      if (idx %in% kids_idx) {
        res <- res + score_tree(tree$kids[[idx]])
      }
    }
  }
  res
}
score_tree(tree)
```
