---
params:
   task_nr: 21
   year: 2015
title: '`r paste("<span>Task", params$task_nr, "<span class = \"back\"><a href = \"index.html\">", fontawesome::fa("home"), "</a></span></span>")`'
author: 
  name: "Thorn Thaler"
  email: "thorn.thaler@thothal.at"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
   force_year <- "2015"
   
   year <- dplyr::coalesce(force_year, format(Sys.Date(), "%Y"))
   
   o_file <- sprintf("%s_%s", year, 
                     tools::file_path_sans_ext(basename(inputFile)))
                     
   rmarkdown::render(inputFile, encoding = encoding, 
                     output_file = o_file, output_dir = here::here("docs"))
   })
output: 
  rmdformats::downcute:
    highlight: tango
    use_bookdown: TRUE
    mathjax: NULL
    lightbox: TRUE
    gallery: TRUE
editor_options: 
  chunk_output_type: console
---

```{css custom-css, echo = FALSE}
.page-content  .figure {
  width: 100%;
}

.back {
  font-size: 2rem;
}

.day-desc {
  border: 2px dotted;
  border-radius: 6px;
  border-color: var(--blockquote-border-color);
  padding: 0 20px;
}
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.align = "center",
                      dev.args = list(bg = "transparent"))
## Define a function to write text in typewriter font
tt <- function(x) {
  if (knitr::is_latex_output()) {
    sprintf("\\texttt{%s}", as.character(x))
  } else if (knitr::is_html_output()) {
    sprintf("<tt>%s</tt>", as.character(x))
  } else {
    x
  }
}
```

# Setup

## Libraries

```{r libs, warning = FALSE}
library(httr)
library(xml2)
library(magrittr)
library(dplyr)
library(purrr)
library(stringr)
library(tidyr)
library(gtools)
```

## Retrieve Data from `r tt("AoC")`


```{r get-data, cache = FALSE, messages = FALSE}
session_cookie <- set_cookies(session = keyring::key_get("AoC-GitHub-Cookie"))
base_url <- paste0("https://adventofcode.com/", params$year, "/day/", params$task_nr)
puzzle <- GET(base_url,
              session_cookie) %>% 
  content(encoding = "UTF-8") %>% 
  xml_find_all("///article") %>% 
  lapply(as.character)

parse_puzzle_data <- function(text_block = readClipboard()) {
  stats <- text_block$input %>% 
    str_extract_all("\\d+") %>% 
    unlist() %>% 
    as.integer() %>% 
    set_names(text_block$input %>% 
                str_remove_all("[0-9: ]+") %>% 
                unlist())
  shop <- do.call(rbind, as.list(text_block$shop)) %>% 
    set_colnames("string") %>% 
    as_tibble()
  cn <- shop %>% 
    filter(!str_detect(string, "\\d")) %>% 
    slice(1L) %>% 
    pull(string) %>% 
    str_split("[:\\s]+") %>% 
    extract2(1L)
  shop <- shop %>% 
    separate_wider_delim(string, delim = regex("\\s+(?!\\+)"), names = cn) %>% 
    mutate(Type = if_else(!str_detect(Armor, "\\d"), Weapons, NA_character_)) %>% 
    fill(Type) %>% 
    mutate(Type = str_remove_all(Type, ":")) %>% 
    filter(str_detect(Cost, "\\d")) %>% 
    mutate(across(Cost:Armor, as.integer)) %>% 
    rename(Name = 1)
  list(stats = stats, shop = shop)
}

puzzle_data <- local({
  input <- GET(paste0(base_url, "/input"),
      session_cookie) %>% 
    content(encoding = "UTF-8") %>% 
    str_split("\n") %>% 
    extract2(1L) %>% 
      keep(nzchar)
  shop <- GET(base_url) %>% 
    content(encoding = "UTF-8") %>% 
    xml_find_all("//pre/code") %>% 
    lapply(as.character) %>% 
    extract2(1L) %>% 
    str_remove_all("</?code>") %>% 
    str_split("\n") %>% 
    extract2(1L) %>% 
    keep(nzchar)
  parse_puzzle_data(list(input = input, shop = shop))
})
```

```{r example-data, eval = interactive(), echo = FALSE}
```

# Puzzle Day `r params$task_nr`

## Part 1

### Description

```{r show-puzzle-a, echo = FALSE, results = "asis"}
cat(puzzle[[1]])
```

### Solution

We create all possible equipment setups and simulate each game. For the winning games, we
select the setup with lowest cost.

```{r get_setups, cache = TRUE}
get_stats <- function(name, shop) {
  name <- unlist(name)
  if (length(name) > 1L) {
    shop %>% 
      filter(Name %in% name) %>% 
      select(Cost:Armor) %>% 
      summarize(across(everything(), sum))
  } else if (is.na(name)) {
    tibble(Cost = 0, Damage = 0, Armor = 0)
  } else {
    shop %>% 
      filter(Name == name) %>% 
      select(Cost:Armor)
  }
}

get_setups <- function(shop) {
  weapons <- shop %>% 
    filter(Type == "Weapons") %>% 
    pull(Name)
  armor <- shop %>% 
    filter(Type == "Armor") %>% 
    pull(Name) %>% 
    c(NA_character_, .)
  rings <- shop %>% 
    filter(Type == "Rings") %>% 
    pull(Name)
  rings <- map(1:2, ~ combinations(length(rings), .x, rings)) %>% 
    map(~ apply(.x, 1, identity, simplify = FALSE)) %>% 
    flatten() %>% 
    c(NA, .)
  setup <- expand.grid(weapon = weapons, armor = armor, stringsAsFactors = FALSE) %>%
    as_tibble() %>%
    rowwise() %>%
    reframe(weapon = weapon, armor = armor, rings = rings) %>% 
    mutate(id = 1:n())
  setup  %>% 
    group_by(id) %>% 
    group_modify(function(.x, ...) {
      weapon_stats <- get_stats(.x$weapon, shop)
      armor_stats <- get_stats(.x$armor, shop)
      ring_stats <- get_stats(.x$rings, shop)
      res <- weapon_stats +
        armor_stats +
        ring_stats
      res %>% mutate(across(Cost:Armor, as.integer))
    }) %>% 
    inner_join(setup, ., by = "id")
}

setups <- get_setups(puzzle_data$shop)
```

```{r get-solution-1}
simulate_game <- function(equipment, boss_stats, hit_points = 100L) {
  boss_damage <- max(boss_stats["Damage"] - equipment %>% pull(Armor), 1L)
  boss_hit_points <- boss_stats["HitPoints"]
  me_damage <- max(equipment %>% pull(Damage) - boss_stats["Armor"], 1L)
  anybody_dead <- FALSE
  while(!anybody_dead) {
    boss_hit_points <- boss_hit_points - me_damage
    if (boss_hit_points <= 0) {
      survived <- TRUE
      anybody_dead <- TRUE
    }
    hit_points <- hit_points - boss_damage
    if (hit_points <= 0) {
      survived <- FALSE
      anybody_dead <- TRUE
    }
  }
  survived
}

find_best_equipment <- function(setups, boss_stats, hit_points = 100L) {
  setups <- setups %>% 
    arrange(Cost)
  for (eq_idx in 1:nrow(setups)) {
    if (simulate_game(setups %>% slice(eq_idx), boss_stats, hit_points)) {
      break
    }
  }
  setups %>% 
    slice(eq_idx)
}

find_best_equipment(setups, puzzle_data$stats, 100L)
```

## Part 2

### Description

```{r show-puzzle-b, echo = FALSE, results = "asis", eval = length(puzzle) > 1}
cat(puzzle[[2]])
```

### Solution

This time we look for the equipment with the highest costs, which leads to our death.

```{r get-solution-2}
find_worst_equipment <- function(setups, boss_stats, hit_points = 100L) {
  setups <- setups %>% 
    arrange(desc(Cost))
  for (eq_idx in 1:nrow(setups)) {
    if (!simulate_game(setups %>% slice(eq_idx), boss_stats, hit_points)) {
      break
    }
  }
  setups %>% 
    slice(eq_idx)
}

find_worst_equipment(setups, puzzle_data$stats, 100L)
```
